services:
  backend:
    container_name: flask_server
    image: flask_server:1.0.0
    build:
      context: ./project/backend
      dockerfile: flask.dockerfile  
    ports:
      - 5000:5000
    environment:
    - PYTHONUNBUFFERED=1  